const lideresData = {
    "COMUNA 1": [
        "JORGE PINEDA",
        "DANIEL GALLEGO",
        "RAFAEL MUÑOZ",
        "HELEN GALLO",
        "JULIANA LONDOÑO",
        "YEISON MAHECHA",
        "CAMILO LÓPEZ",
        "ALBEIRO VENTERO",
        "OSCAR BETANCUR IND KEVIN"
    ],
    "COMUNA 2": [
        "FABIAN BARRIOS",
        "VIVIANA RAMIREZ",
        "VICTOR MAZO",
        "YARSI BENITEZ",
        "MONICA ALVAREZ",
        "HERMES GARCIA",
        "JHON FERNANDO GARCIA",
        "JULIAN SALAZAR",
        "PABLO ZAPATA TERCERA EDAD",
        "RICHARD ACEVEDO",
        "HERNAN MEJIA",
        "ANDRES FAMA",
        "ANGELO ZAPATA",
        "EDWIN VELEZ",
        "EIMAR ATEHORTUA",
        "DANIELA GIRALDO",
        "PAOLA GIRALDO",
        "GLADIS ALVAREZ",
        "ERIKA ALVERZ",
        "MARIO CARDONA",
        "LUZ ELENA PASOS",
        "ALEX TABORDA",
        "TERESA ARBELAEZ",
        "JORGE CRESPO",
        "CARLOS OCAMPO",
        "SANDRA MURILLO",
        "MARIANA RIOS",
        "RUBEN BENJUMEA",
        "Frank Alexander Taborda M",
        "Sandra Milena Murillo Osorio",
        "Angelica Oviedo Rangel",
        "ELIMELECK CORREA ARROYAVE"
    ],
    "COMUNA 3": [
        "CRISTIAN ARDILA SENA",
        "YENY ARIAS",
        "ALEJANDRA AGUIRRE",
        "JOHAN EXCANDIDATO EDIL",
        "DARIO YARCE",
        "LUZ OTALVARO",
        "JENNIFER GARCIA",
        "ALEXADER ECHEVERRI",
        "LUISA FERNANDA VALENCIA",
        "RAFAEL ANTONIO SOSA",
        "ERNESTO ALONSO MUNERA",
        "Alver Arias",
        "ANDERSON OSPINA IND KEV",
        "EALEN VIVIANA CORREA"
    ],
    "COMUNA 4": [
        "MIRTA AIDE",
        "VALENTINA CALLEJAS",
        "YASMIN LOPEZ",
        "LUIS UPEGUI",
        "NATALIA RIOS",
        "MARIA LLOREDA",
        "SUSANA RIVERA",
        "LUCAS RESTREPO",
        "Valentina Callejas franco",
        "John Albeiro Castañeda Gonzalez",
        "Julián Sebastián Salazar Marín",
        "Esaú Pulgarín",
        "Sindy Vanesa Hurtado Hurtado",
        "Fernando Pulgarín Castaño",
        "LUIS CIFUENTES",
        "DANIEL PERFORMAS",
        "MILENA VERGARA ESPOSA MONTI",
        "PITER TORRES",
        "LUCY OTALVARO",
        "RODRIGO MARIN",
        "JORGE PINEDA",
        "OSCAR BETANCUR IND KEVIN"
    ],
    "COMUNA 5": [
        "ELIANA EX EDIL",
        "JULIAN CALLE",
        "FRANCY GARCIA",
        "ANDREA ALVAREZ - LAURA",
        "VICTOR GIRALDO EX EDIL",
        "ALBEIRO VASQUEZ",
        "CARLOS HENAO (llamar a JUICIO)",
        "JHON DARIO",
        "CAROLINA GARCIA",
        "ADOLFO EL NEGRO",
        "MATEO TUBERQUIA INDEP KEVIN",
        "SNEYDER LOPEZ INDEP KEVIN"
    ],
    "COMUNA 6": [
        "DORIAN",
        "CARLOS DELGADO",
        "JIMENA",
        "MONCHO",
        "SANTIAGO JUANCHO",
        "YERSID CASAD",
        "KELLYN ATEHORTUA",
        "Cristian camilo Medina caicedo",
        "ANDERSON OSPINA INDEP KEVIN",
        "JUAN DIEGO CORREA INDEP  KEVIN",
        "JUAN PABLO CALLE",
        "MELISSA MEDELLIN",
        "IVAN MONSALVE INDEP KEVIN",
        "WITER ELENA SERNA INDEP KEVIN",
        "FABIO RUIZ IND KEVIN"
    ],
    "COMUNA 7": [
        "CLARIBEL",
        "TYRON POWER",
        "JHONATHAN QUICENO",
        "SERGIO MIRANDA",
        "LUZ DARY URIBE",
        "CAMILO CASTAÑO",
        "NINSON ALARCON",
        "ISABELLA ESPINOZA",
        "YAIR ARROYAVE",
        "ANDRÉS LÓPEZ",
        "Diana Maria guzmán García",
        "Claribel Munera PereañezC",
        "Sara Valentina Torres",
        "KEVIN CONTRERAS",
        "FERNEY AGUDELO INDEP KEVIN",
        "MILENA",
        "SANTIAGO RIOS INDEP KEVIN",
        "JUAN ESTEBAN PEREZ INDEP KEVIN",
        "ALEXIS GARCES INDEP KEVIN",
        "MONICA FLOREZ CARO INDEP KEVIN"
    ],
    "COMUNA 8": [
        "MARCELA JARAMILLO",
        "MAICOL FORONDA"
    ],
    "COMUNA 9": [
        "JORGE DAVID ZULUAGA",
        "LILIAN MOSQUERA",
        "MARICELA RENTERIA",
        "MAICOL FORONDA",
        "DIEGO BERMUDEZ",
        "DIEGO HOYOS",
        "JOSEPH CIFUENTES",
        "OLGA RAMIREZ",
        "BERNARDO TABARES",
        "JORGE GOMEZ",
        "ALEXANDER RIOS",
        "ROMERO",
        "LEON MANRIQUE",
        "FERIA",
        "LIBARDO VALLEJO",
        "GLORIA NANCY CIFUENTES",
        "LUNA",
        "FREDY ALZATE",
        "KRISTIAN MEDINA",
        "LIBARDO VALLEJO  PARTIDO LIBERAL",
        "LUISA EX EDIL VERDE"
    ],
    "COMUNA 10": [
        "EDWIN VALDERRAMA",
        "DUBERNEY ZABALA",
        "MARIA EUGENIA CHECHERECHEROS",
        "ANDRES RAMIREZ",
        "OSCAR JACOBO",
        "DIANA VERONICA PATIÑO",
        "DAVID ZAFARRANCHO",
        "LUIS - ARTISTAS",
        "WBEIMAR GUARIN",
        "FREDDY CARDENAS"
    ],
    "COMUNA 11": [
        "DIEGO RIASCOS",
        "BEATRIZ MORALES",
        "ROBERT RUIZ",
        "LINA MASUERA",
        "FARID BEDOYA",
        "VALENTINA - ZAFARRANCHO",
        "Beatriz Helena Morales Gaviria",
        "Juan Manuel Quiroz Zapata",
        "Wilson Buitrago Giraldo",
        "Paula Andrea gonzalez",
        "Fernando Pulgarín Castaño",
        "Yucely Yurgaky Sánchez",
        "Jaiberth Yepes",
        "Yomar Benitez",
        "ALEJANDRO ARANGO INDEP KEVIN"
    ],
    "COMUNA 12": [
        "MARLON CARVAJAL",
        "LEIDY FERNANDA ZAPATA",
        "JOSHUA ALZATE",
        "DANIEL GIL  EX VERDE",
        "JORGE PIZZA",
        "GLORIA GARCIA (La profe) INDEP KEVIN",
        "ANA RENTERIA INDEP KEVIN"
    ],
    "COMUNA 13": [
        "YEI PUERTA",
        "CESAR ARANGO",
        "ALBERT ARIAS",
        "DIEGO BRAN"
    ],
    "COMUNA 14": [
        "JULIO (JAIVER)",
        "STANLI",
        "CARMEN",
        "SERGIO GARCIA - PAPA DE LUCAS",
        "LEON ENVÍA LKISTADO",
        "YULIETH ACEVEDO",
        "Byron Miranda"
    ],
    "COMUNA 15": [
        "Alex Usuga",
        "VERONICA BEDOYA EX  CANDIDATA ASAMBLEA",
        "Evento en el centro comunitario de Barrio Antioquia, con los líderes de la izquierda"
    ],
    "COMUNA 16": [
        "JAIVER YEPES",
        "DANIEL GIL",
        "ALBEIRO QUERUBIN",
        "DANIELA PRADA INDEP ELKIN",
        "FABIAN INDEP KEVIN",
        "OSCAR BETANCUR IND KEVIN"
    ],
    "COMUNA 70 - CORREGIMIENTO ALTAVISTA": [
        "DEISY MUÑOZ",
        "RUBIELA",
        "LUZ MARY"
    ],
    "COMUNA 60 - CORREGIMIENTO SAN CRSITOBAL": [
        "ANA MARIA RESTREPO",
        "DIANA DISNEY",
        "LUZ DARY",
        "JORGE PAREDES",
        "JONIER QUICENO EX CANDIDATO CONCEJO"
    ],
    "COMUNA 80 - CORREGIMIENTO SAN ANTONIO": [
        "WILSON, FABIO Y GUILLERMO HACEN LISTADO}",
        "EFREN ALVAREZ",
        "JOAQUIN ARIAS",
        "DIEGO TAFUR Y ESTEFANÍA",
        "LEONARDO GOEZ INDEP KEVIN"
    ],
    "COMUNA 50 - CORREGIMIENTO SAN SEBASTIA": [
        "SAUL",
        "EDWIN VALDERRAMA",
        "CRISTINA PUERTA"
    ],
    "COMUNA 90 - CORREGIMIENTO SANTA ELENA": [
        "WALTER PEREZ",
        "JULIO BICI PIZZA",
        "DORIAN",
        "JIMENA",
        "SILLETEROS - YOMAR"
    ]
};